# Generated by Django 2.0.9 on 2020-06-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataoceanuser',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
